# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Location.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
sys.path.append('..')
import Location_common_pb2 as Location__common__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Location.proto',
  package='ros_location',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eLocation.proto\x12\x0cros_location\x1a\x15Location_common.proto\"\xe5\x03\n\x08Location\x12/\n\x08position\x18\x01 \x01(\x0b\x32\x1d.ros_location.common.PointLLH\x12\r\n\x05pitch\x18\x02 \x01(\x01\x12\x0c\n\x04roll\x18\x03 \x01(\x01\x12\x0f\n\x07heading\x18\x04 \x01(\x01\x12\x35\n\x0flinear_velocity\x18\x05 \x01(\x0b\x32\x1c.ros_location.common.Point3D\x12\x38\n\x12linear_accerlation\x18\x06 \x01(\x0b\x32\x1c.ros_location.common.Point3D\x12\x36\n\x10\x61ngular_velocity\x18\x07 \x01(\x0b\x32\x1c.ros_location.common.Point3D\x12\x10\n\x08rtk_flag\x18\x08 \x01(\x05\x12\x11\n\todom_type\x18\t \x01(\x05\x12\x16\n\x0e\x61uxiliary_type\x18\n \x01(\x05\x12\x1b\n\x13location_valid_flag\x18\x0b \x01(\x05\x12\x12\n\norigin_lat\x18\x0c \x01(\x01\x12\x12\n\norigin_lon\x18\r \x01(\x01\x12\x33\n\x0cutm_poisiton\x18\x0e \x01(\x0b\x32\x1d.ros_location.common.PointENU\x12\x1a\n\x12\x63hange_origin_flag\x18\x0f \x01(\x05\x62\x06proto3')
  ,
  dependencies=[Location__common__pb2.DESCRIPTOR,])




_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='ros_location.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='ros_location.Location.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='ros_location.Location.pitch', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='ros_location.Location.roll', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='ros_location.Location.heading', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_velocity', full_name='ros_location.Location.linear_velocity', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear_accerlation', full_name='ros_location.Location.linear_accerlation', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='ros_location.Location.angular_velocity', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rtk_flag', full_name='ros_location.Location.rtk_flag', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='odom_type', full_name='ros_location.Location.odom_type', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auxiliary_type', full_name='ros_location.Location.auxiliary_type', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location_valid_flag', full_name='ros_location.Location.location_valid_flag', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin_lat', full_name='ros_location.Location.origin_lat', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin_lon', full_name='ros_location.Location.origin_lon', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utm_poisiton', full_name='ros_location.Location.utm_poisiton', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='change_origin_flag', full_name='ros_location.Location.change_origin_flag', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=541,
)

_LOCATION.fields_by_name['position'].message_type = Location__common__pb2._POINTLLH
_LOCATION.fields_by_name['linear_velocity'].message_type = Location__common__pb2._POINT3D
_LOCATION.fields_by_name['linear_accerlation'].message_type = Location__common__pb2._POINT3D
_LOCATION.fields_by_name['angular_velocity'].message_type = Location__common__pb2._POINT3D
_LOCATION.fields_by_name['utm_poisiton'].message_type = Location__common__pb2._POINTENU
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'Location_pb2'
  # @@protoc_insertion_point(class_scope:ros_location.Location)
  ))
_sym_db.RegisterMessage(Location)


# @@protoc_insertion_point(module_scope)
